#!/usr/bin/env python


import sys
import numpy as np
import scipy as sp
import pylab as pl
import cv2

# filename = "2013-11-24 18.40.14.mp4"
filename = "2013-11-25 00.55.36.mp4"

if __name__ == "__main__":
    cam = cv2.VideoCapture(filename)
    ret1, im1 = cam.read()


    NN = 150
    sh = (NN, im1.shape[0], im1.shape[1], 3)

    ims = np.zeros(sh)

    ims[0,:,:,:] = im1.copy()
    sys.stdout.write('000')
    sys.stdout.flush()

    for i in range(1,NN):
        sys.stdout.write('\b\b\b%03d' % i)
        sys.stdout.flush()
        ret, img = cam.read()
        if (type(img) == type(None)):
            break
        ims[i] = img.copy()

    sys.stdout.write('\n')
